site_name: Levant vACC controller library
site_url: https://levantvacc.library
repo_url: https://github.com/Levant-vACC/Levant-vACC-library
repo_name: levant-vacc/library
theme:
  name: material
  palette: 
    scheme: slate
    primary: red
    accent: deep purple
  logo: docs/assets/logo.png
extra:
  social:
